### ISSUE TITLE
Question on Congestion Window and CHECKSUM calculation and `connect` method input

### ISSUE THREAD

**Issue by Jaredanwolfgang** [SUSTech-HPCLab/CS305-2024Spring-FinalProject#1]
**Question 1:**
If we implement Congestion Window, should we add the Congestion Window size in the Header? And should we calculate the size of Congestion Window size in our CHECKSUM? (In the RDTHeader the CWND field seems to be removed)

**Question 2:**
In the example given in the description, `connect()` method does not have an according input, while in the example `RDT.py` file `connect(address: (str, int))` method has an input address. Is this a mistake or something else? 

Because from my knowledge, we are to instantiate two sockets which should be both server and client and therefore we need to bind the two sockets to two addresses. Using `connect()` method means that we are trying to connect to the target server address as the client side. I think the correct example code for client should be:
```
# As a Client
bind_addr =  ("123.4.5.7", 12345)
target_addr = ("123.4.5.6", 12345)
socket = RDTSocket(...)
socket.bind(bind_addr)
socket.connect(target_addr)
```

**Comment by jzxycsjzy** [comment]
> **Question 1:** If we implement Congestion Window, should we add the Congestion Window size in the Header? And should we calculate the size of Congestion Window size in our CHECKSUM? (In the RDTHeader the CWND field seems to be removed)
> 
> **Question 2:** In the example given in the description, `connect()` method does not have an according input, while in the example `RDT.py` file `connect(address: (str, int))` method has an input address. Is this a mistake or something else?
> 
> Because from my knowledge, we are to instantiate two sockets which should be both server and client and therefore we need to bind the two sockets to two addresses. Using `connect()` method means that we are trying to connect to the target server address as the client side. I think the correct example code for client should be:
> 
> ```
> # As a Client
> bind_addr =  ("123.4.5.7", 12345)
> target_addr = ("123.4.5.6", 12345)
> socket = RDTSocket(...)
> socket.bind(bind_addr)
> socket.connect(target_addr)
> ```

Q1: You don't have to add CWND to the header since it is not the necessary data field in the header. If you want to do that, you should add it in the `Reserved` field and it should be calculated in CHECKSUM.

Q2: You are correct. We have fixed it.

Thanks for your attention and we're sorry about our mistakes. If you have any questions, please feel free to contact us.

**Comment by Jaredanwolfgang** [comment]
Thanks for your reply.
